"""update movie model

Revision ID: 9e4e161bedee
Revises: aceb0285e749
Create Date: 2024-01-15 15:49:02.707120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e4e161bedee'
down_revision = 'aceb0285e749'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genre', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('release_year', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('director', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.drop_column('director')
        batch_op.drop_column('release_year')
        batch_op.drop_column('genre')

    # ### end Alembic commands ###
